# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions

name: Continuous Integration

on:
  push:
    branches:
      - node

jobs:
  continuous-integration:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install NPM Packages
        run: npm install
      - name: Tests
        run: npm run test
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test/junit.xml
      - name: Deploy (dry)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy:dry